### ISSUE TITLE
Implementierung Aktienpage

### ISSUE THREAD

**Issue by codajoda** [SE-TINF22B2/G3-ApeRepublic#119]
**Aufgabe**
Hierbei soll die Aktien-Seite implementiert werden. 

**Beschreibung**

Diese umfasst 
- die Darstellung des Aktiengraphen für das jeweilige Unternehmen
- die Unternehmensinformationen
- den Aktienkurs
- den eigenen Anteil an das Unternehmen
- den Kauf und Verkauf der Aktie (Dies verläuft auf einer neuen Seite)

**Alternativen?**

**Comment by MatejEvc** [comment]
Beschreibung hinzufügen!

**Comment by MatejEvc** [comment]
Was tut sich hier?

**Comment by codajoda** [comment]
Dieses Issue kann geschlossen werden, wurde nur noch nicht gemacht.
