### ISSUE TITLE
Servicestruktur entwerfen

### ISSUE THREAD

**Issue by Marc738** [SE-TINF22B2/G3-ApeRepublic#120]
Im Server die Struktur der Serviceklassen definieren:
* Welche sind sinnvoll?
* Was soll angeboten werden/was nicht?
* Welche Schnittstellen zu anderen Komponenten soll es geben?

> Keine zu detailierten Entwurfspläne für Spielraum!

Ergebnis:
* UserAuth: https://miro.com/app/board/uXjVKRFFdR8=/?share_link_id=316855479889

**Comment by MatejEvc** [comment]
Template verwenden!
