### ISSUE TITLE
Implementierung Willkommen Seite

### ISSUE THREAD

**Issue by elnaz-gharoon** [SE-TINF22B2/G3-ApeRepublic#122]
**Aufgabe**

Implementierung willkommen Seite

**Beschreibung**
Es gibt auf diese Seite 2 Buttons, der Benutzer kann sich auf diese Seite entweder registrieren oder mit seiner Konto anmelden

**Alternativen?**

Login Seite

**Comment by MatejEvc** [comment]
Beschreibung hinzufügen
