### ISSUE TITLE
Implementierung Passwort vergessen Seite

### ISSUE THREAD

**Issue by elnaz-gharoon** [SE-TINF22B2/G3-ApeRepublic#137]
Aufgabe
Implementierung Passwort vergessen seite

Beschreibung
wenn win Benutzer sein Passwort vergiss, kann er es auf diese Seite erneut erstellen.

Alternativen?

**Comment by MatejEvc** [comment]
BESCHREIBUNG!
Die Prio wurde **wie besprochen** auf low statt high gesetzt
