### ISSUE TITLE
Realtime Aktienpreise API mit finnhub.io verbinden

### ISSUE THREAD

**Issue by MatejEvc** [SE-TINF22B2/G3-ApeRepublic#144]
**Beschreibung**
Es soll ein WebSocket für die Anbindung an finnhub.io entwickelt werden. Diese soll regelmäßige Updates von finnhub.io bekommen.

**Alternativen/Sonstiges**
Andere APIs, allerding Limitiert in Calls und kein WebSocket

**Comment by roland-KA** [comment]
Auch hier die Frage: Wenn es als "Done" gekennzeichnet wurde, warum kann man die Issue nicht schließen?
