### ISSUE TITLE
Daten in DB speichern

### ISSUE THREAD

**Issue by culmets** [SE-TINF22B2/G3-ApeRepublic#158]
**Beschreibung**
Aktuell können Daten aus dem Backend abgefragt aber noch nicht gespeichert werden. In einem Fall liegt es wahrscheinlich an der Generierung des Primary Keys. Im anderen Fall sieht es im Backend so aus als wäre der Datensatz gespeichert worden, taucht aber in der DB nicht auf.

**Alternativen/Sonstiges**

**Comment by MatejEvc** [comment]
Evtl. sollen den Issue aufteilen. Es fehlt welche Daten genau angefragt werden können. Wäre hilfreich für einen Besseren Überblick über dem Status des Projekts/Anbindung der DB

@Marc738 wollte auch dabei sein
