### ISSUE TITLE
Implementierung main Seite

### ISSUE THREAD

**Issue by elnaz-gharoon** [SE-TINF22B2/G3-ApeRepublic#159]
Beschreibung:
Hierbei soll die Main-seite implementiert werden

**Comment by MatejEvc** [comment]
Bitte die Phase, SP, Iteration, Milestone einfügen
Ist diese Story für diesen Milestone notwendig?
Was ist die Main-Seite? Portfolio-Seite?

**Comment by elnaz-gharoon** [comment]
@MatejEvc  Graph wird in Main Seite angezeigt, sowie anderen Button wie Tabelle und so weiter. Das wurde vorher implementiert, es soll aber wieder verbessern und entwickeln werden

**Comment by MatejEvc** [comment]
Ebenfalls sollen die Issues aufgeteilt werden:
z.B. statt der ganzen Seite können die Issues auf die Components aufgeteilt werden.
