### ISSUE TITLE
FrontEnd-Struktur dokumentieren

### ISSUE THREAD

**Issue by codajoda** [SE-TINF22B2/G3-ApeRepublic#176]
**Beschreibung**

Dokumentation des FrontEnds in Bezug auf Routing (Von welcher Seite kommt wann/wie auf die anderen Seiten?)

https://github.com/SE-TINF22B2/G3-ApeRepublic/wiki/Projekthandbuch

**Alternativen/Sonstiges**

**Comment by MatejEvc** [comment]
SP, Iteration, Milestone, Phase hinzufügen!
