### ISSUE TITLE
Code Dokumentation

### ISSUE THREAD

**Issue by Marc738** [SE-TINF22B2/G3-ApeRepublic#193]
**Beschreibung**
Dokumentation der Codestruktur.

**Alternativen/Sonstiges**
Ne, muss gemacht werden

**Comment by elnaz-gharoon** [comment]
@Marc738 gibt es auf wiki Pages zum FE Code Doku und BE Code Doku?

**Comment by Marc738** [comment]
> @Marc738 gibt es auf wiki Pages zum FE Code Doku und BE Code Doku?

Ne, noch nicht so wie er will.
