### ISSUE TITLE
Register Flowchart erstellen

### ISSUE THREAD

**Issue by Marc738** [SE-TINF22B2/G3-ApeRepublic#58]

**Comment by elnaz-gharoon** [comment]
1- Der Benutzer hat noch nicht ein Account
2- Der Benutzer besucht der Register Page
3-Erstellen ein Account ermöglicht durch Benutzername und ein sicheres Passwort

**Comment by elnaz-gharoon** [comment]
https://miro.com/app/board/uXjVNQdfK18=/
