### ISSUE TITLE
ER-Modell erstellen

### ISSUE THREAD

**Issue by MatejEvc** [SE-TINF22B2/G3-ApeRepublic#63]
![Image](https://github.com/SE-TINF22B2/G3-ApeRepublic/assets/147487079/b29d5b25-f376-4d17-bb75-bdd506673a4a)

Code: https://github.com/SE-TINF22B2/G3-ApeRepublic/blob/8d3dd5f7832967dd4baadff28ed0a2c8f698d7d4/ERDPlus.erdplus
Webseite: [ERDPlus.com](https://erdplus.com/standalone)

**Comment by Marc738** [comment]
In Deutsch umschreiben

**Comment by culmets** [comment]
Ist jetzt Deutsch
