### ISSUE TITLE
Login Use Case

### ISSUE THREAD

**Issue by MatejEvc** [SE-TINF22B2/G3-ApeRepublic#88]
Beschreibung: 
Erstellen loginUsecase

**Comment by MatejEvc** [comment]
Müssen ausführlicher bearbeitet werden

**Comment by elnaz-gharoon** [comment]
@MatejEvc  reicht es nicht aus ? Hauptverlauf habe ich als Diagramme berschreicbt 
https://github.com/SE-TINF22B2/G3-ApeRepublic/wiki/Use-Cases

**Comment by MatejEvc** [comment]
Für beide Use Cases Alternativer Ablauf und Nachbedingung hinzufügen
Use Case getrennt schreiben
Nicht Use Case Login Seite, nur Login
